export enum InputType {
  Text = 'text',
  Password = 'password',
  Email = 'email',
  Number = 'number',
  Tel = 'tel',
  Url = 'url',
  Date = 'date',
  Time = 'time',
  DatetimeLocal = 'datetime-local',
  Month = 'month',
  Week = 'week',
  Range = 'range',
  Color = 'color',
  File = 'file',
  Hidden = 'hidden',
  Search = 'search',
  Submit = 'submit',
  Reset = 'reset',
  Button = 'button',
}
